[general]
import = [ "~/.config/alacritty/catppuccin-mocha.toml", "~/.config/alacritty/host-specific.toml" ]

# [terminal.shell]
# program = "tmux"
# args = ["new-session", "-A", "-D", "-s", "ï€• default"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

# opacity = 0.7
# blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font"
#normal.family = "Hack Nerd Font"
#normal.family = "MesloLGS Nerd Font"
# normal.family = "FiraCode Nerd Font Mono"
# normal.family = "FiraCode Nerd Font Mono"
# normal.family = "DroidSansM Nerd Font Mono"
# normal.style = "Medium"

